"""Initial schema

Revision ID: c44fa666f1b1
Revises: 
Create Date: 2026-09-04 16:19:13.087147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c44fa666f1b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_host', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('added_by', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_host')
    )
    op.create_table('api_keys',
    sa.Column('key_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key_id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('audit_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('origin_url', sa.Text(), nullable=False),
    sa.Column('cache_result', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('bytes_served', sa.BigInteger(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('client_ip_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_audit_events_object_id', 'audit_events', ['object_id'], unique=False)
    op.create_index('ix_audit_events_timestamp', 'audit_events', ['timestamp'], unique=False)
    op.create_table('benchmark_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_name', sa.Text(), nullable=False),
    sa.Column('origin_url', sa.Text(), nullable=False),
    sa.Column('origin_speed_mbps', sa.Float(), nullable=False),
    sa.Column('cache_speed_mbps', sa.Float(), nullable=False),
    sa.Column('origin_duration_s', sa.Float(), nullable=False),
    sa.Column('cache_duration_s', sa.Float(), nullable=False),
    sa.Column('measured_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('policy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('licence', sa.Text(), nullable=False),
    sa.Column('access_tier', sa.Text(), nullable=False),
    sa.Column('embargo_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('origin_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('object_id')
    )
    op.create_table('cache_entries',
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('origin_url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('cached_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_accessed', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cache_entries')
    op.drop_table('policies')
    op.drop_table('benchmark_results')
    op.drop_index('ix_audit_events_timestamp', table_name='audit_events')
    op.drop_index('ix_audit_events_object_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('api_keys')
    op.drop_table('allowlist')
    # ### end Alembic commands ###
